### ISSUE TITLE
? and apg Discord messages not showing on votes.

### ISSUE THREAD

**Issue by Jkqr** [paradoxally/Trivia-Swift#15]
Title. Only text numbers are showing up 1, 2, 3 etc. Not 3apg and 2?

**Comment by Jkqr** [comment]
Would be great if it didn't need a space and if you added 2apg etc.

**Comment by paradoxally** [comment]
The former behavior can be changed, I will edit the regex and add this in.

The latter behavior is normal. I made it so it counts non-confident votes as 0.25 of a vote, and that way you need at least 2-3 for it to show up (because it's rounded up). This avoids a random 2? that are usually guesses and not confident answers. If you don't like how this is implemented, change the value given to non-confident votes. This can be found in the following enum:

```
private enum TriviaConfidence: Float {
        case confident = 1.0
        case notConfident = 0.25
    }
```
